platform :ios, '8.0'
use_frameworks!

target 'FinalProject' do
use_frameworks!
pod 'Kanna', '~> 4.0.0'
pod 'AFNetworking', '~> 2.6'
pod 'ORStackView', '~> 3.0'
pod 'SwiftyJSON', '~> 2.3'
pod 'Alamofire', '~>4 .4'
end

